---
title: "gerrymanderdem Report"
author: "Cory Hertog"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{gerrymanderdem Report}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction
This package uses 2010 census tract level demographic data in conjunction with federal, state upper house, and state lower house legislative voting boundaries to better understand the demographic makeup of each of these political areas. It creates three `SpatialPolygonDataFrames`, one for each type of legislative body, that contain voting age (18 and Over) data total population, White population, Back population, American Indian population, Asian population, Hawaiian/pacific islander and Hispanic population for each of the districts within that legislative body. This can be done for all 48 contiguous states in the United States. 

The development of this package was originally thought of by Sam Wang & Brian Remlinger at the [Princeton Gerrymandering Project](http://gerrymander.princeton.edu/). Gerrymandering, which involves drawing the boundaries of legislative districts to benefit one party or the other, is a current hot topic in the US with challenges to [Wisconsin's state redistricting in 2012](https://www.reuters.com/article/us-usa-court-election/justice-kennedy-on-hot-seat-in-major-voting-rights-case-idUSKCN1C81P2) being debated in the Supreme Court during the development of this package. This case could have lasting effect on how political voting districts are drawn in the US. However, gerrymandering has occurred in the US for most of its history, but a workable standard for determining if a district is gerrymandered remains elusive.

Understanding how gerrymandering districts affects the distribution of racial groups within legislative district is an important step to understanding the problem. Techniques such as "stacking" or "cracking" can diminish the ability for minority populations to gain representation in legislative boundaries.  In Baldus v. Brennan, a federal judge ruled that the way certain assembly districts had been drawn in Milwaukee had effectively ['cracked' Latino voters](https://www.propublica.org/article/partisan-gerrymandering-is-still-about-race).

### Necessary Project Pre-Work
In order for this package to work, the user needs to do two preemptive actions before starting.  The first is to determine the Federal Information Processing Standard Publication (FIPS) code for the US state of interest.  FIPS codes can be obtained form the [census](https://www.census.gov/geo/reference/ansi_statetables.html) website. 

The second step will be to obtain a census key from this website: [https://api.census.gov/data/key_signup.html](https://api.census.gov/data/key_signup.html).  This key allows the user to obtain access to the census data provided by the package `tidycensus`, which is a required package for this package.

## Methods

## Results

## Discussion
